### ISSUE TITLE
Alt and AltGr does not report pressed events, only release.

### ISSUE THREAD

**Issue by BOLL7708** [jeppevinkel/WinUtilities#2]
Hello!

I am using your library in my project, specifically the key hook!

First though, I have this problem, where I get only the `OnKeyReleaseEvent` and not the `OnKeyPressEvent`  for the keys `LEFT_MENU` and the combined key Alt Gr which is `LEFT_MENU` and `LEFT_CONTROL` together.

Do you see this on your end, or is it actually working as intended?

**Comment by jeppevinkel** [comment]
The reason is system keys don't come with the same event as normal keys, so that has now been fixed with version 1.1.0.

The `LEFT_MENU` triggering a `LEFT_CONTROL` event seems to be a keyboard layout issue in Windows. `ALT GR` isn't an actual key in Windows, so what happens is it emulates a `Ctrl+Alt` press.

**Comment by BOLL7708** [comment]
Can confirm it appears to work now, thanks! 🥳
